<a href="https://colab.research.google.com/github/TranToQuePhuong/AI_Lab08/blob/master/3_Lab_MLP_for_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multilayer Perceptron for Iris dataset

- Nguyễn Hữu Vũ 
- Nhóm nghiên cứu về AI đại học Bách Khoa Tp. Hồ Chí Minh

In [21]:

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [22]:
# Load the iris dataset
iris = datasets.load_iris()

# Create our X and y data
X = iris.data
y = iris.target

## 1) Khám phá dữ liệu

In [23]:
X.shape

(150, 4)

In [24]:
y.shape

(150,)

In [25]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [26]:
# View the first five observations of our y data
y[:5]

array([0, 0, 0, 0, 0])

In [27]:
# Split the data into 70% training data and 30% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [28]:
X_train[:5]

array([[4.9, 2.5, 4.5, 1.7],
       [5.5, 2.5, 4. , 1.3],
       [5.1, 2.5, 3. , 1.1],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.4, 1.5, 0.2]])

## 2) Chuẩn bị dữ liệu

In [29]:
# Train the scaler, which standarizes all the features to have mean=0 and unit variance
sc = StandardScaler()
sc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [30]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_std = sc.transform(X_test)

In [31]:
X_train_std[:5]

array([[-1.21660018, -1.26092449,  0.4230325 ,  0.67778903],
       [-0.44396095, -1.26092449,  0.1308061 ,  0.13555781],
       [-0.95905377, -1.26092449, -0.4536467 , -0.13555781],
       [-1.21660018,  0.10165258, -1.3303259 , -1.35557806],
       [-1.08782697,  0.78294111, -1.3303259 , -1.35557806]])

In [32]:
X_test_std[:5]

array([[-1.47414659,  0.32874875, -1.27188062, -1.35557806],
       [-1.47414659,  0.32874875, -1.44721646, -1.35557806],
       [-0.18641454,  1.69132582, -1.21343534, -1.22002025],
       [ 0.45745148, -0.57963596,  0.59836835,  0.81334684],
       [ 1.74518352, -0.1254436 ,  1.18282115,  0.54223122]])

## 3) Xây dựng model Perceptron

In [33]:
# Create a perceptron object with the parameters: 40 iterations (epochs) over the data, and a learning rate of 0.1
ppn = Perceptron(n_iter_no_change=40, eta0=0.1, random_state=0)



In [34]:

# Train the perceptron
ppn.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
           fit_intercept=True, max_iter=1000, n_iter_no_change=40, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [35]:
#The actual number of iterations to reach the stopping criterion. For multiclass fits, it is the maximum over every binary fit.
ppn.n_iter_ 

49

##### Prediction

In [36]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test_std)
y_pred

array([0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2, 0, 1, 2, 2, 1, 2, 2, 0, 0, 2,
       2])

In [37]:
# View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.87


## 4) Xây dựng model MLPClassifier

In [38]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=(8,5 ), activation='tanh', solver='sgd', 
                    alpha=0.0000001, batch_size=4, learning_rate='constant', learning_rate_init=0.005, 
                    power_t=0.5, max_iter=500, shuffle=True, random_state=11, tol=0.00001, 
                    verbose=True, warm_start=False, momentum=0.8, nesterovs_momentum=True, 
                    early_stopping=False, validation_fraction=0.2, 
                    beta_1=0.9, beta_2=0.999, epsilon=1e-08)


In [39]:

# Train the perceptron
clf.fit(X_train_std, y_train)

Iteration 1, loss = 1.07716441
Iteration 2, loss = 0.85922656
Iteration 3, loss = 0.72572601
Iteration 4, loss = 0.63832049
Iteration 5, loss = 0.57435686
Iteration 6, loss = 0.52922345
Iteration 7, loss = 0.49391923
Iteration 8, loss = 0.46494054
Iteration 9, loss = 0.43861982
Iteration 10, loss = 0.41278833
Iteration 11, loss = 0.38865385
Iteration 12, loss = 0.36634762
Iteration 13, loss = 0.34367166
Iteration 14, loss = 0.32080249
Iteration 15, loss = 0.29977307
Iteration 16, loss = 0.28053218
Iteration 17, loss = 0.26140939
Iteration 18, loss = 0.24518720
Iteration 19, loss = 0.23104921
Iteration 20, loss = 0.21402383
Iteration 21, loss = 0.20073701
Iteration 22, loss = 0.19011813
Iteration 23, loss = 0.18072813
Iteration 24, loss = 0.16771376
Iteration 25, loss = 0.15837190
Iteration 26, loss = 0.15124634
Iteration 27, loss = 0.14250117
Iteration 28, loss = 0.14000787
Iteration 29, loss = 0.12932775
Iteration 30, loss = 0.12318969
Iteration 31, loss = 0.11758731
Iteration 32, los

MLPClassifier(activation='tanh', alpha=1e-07, batch_size=4, beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(8, 5), learning_rate='constant',
              learning_rate_init=0.005, max_fun=15000, max_iter=500,
              momentum=0.8, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=11, shuffle=True, solver='sgd',
              tol=1e-05, validation_fraction=0.2, verbose=True,
              warm_start=False)

In [40]:
clf.classes_ 

array([0, 1, 2])

In [41]:
clf.n_layers_ 

4

In [42]:
clf.n_outputs_ 

3

In [43]:
clf.out_activation_ 

'softmax'

- 1 input, 2 hidden, 1 ouput: => 4
- Thông thường trong Neural Networks, sẽ ko tính input layers, nên  trong Neural Networks, trường hợp này số Layers sẽ là 3

In [44]:
# Evaluate acuracy on test data
score = clf.score(X_test_std,y_test)
print("Acuracy (on test set) = ", score)

Acuracy (on test set) =  0.9333333333333333


- Ta thấy chỉ cần tăng #Layers, #Units độ chính xác sẽ tăng cao